version: '3.8'

services:
  # Primeiro container da aplicação
  app1:
    build: ./projeto-web            # Caminho onde está o Dockerfile
    container_name: app1
    environment:
      SERVER_NAME: "Servidor 1"     # Envia esse nome como variável de ambiente
    ports:
      - "5001:5000"                 # Porta externa 5001 aponta para porta interna 5000

  # Segundo container da aplicação
  app2:
    build: ./projeto-web
    container_name: app2
    environment:
      SERVER_NAME: "Servidor 2"
    ports:
      - "5002:5000"

  # Terceiro container da aplicação
  app3:
    build: ./projeto-web
    container_name: app3
    environment:
      SERVER_NAME: "Servidor 3"
    ports:
      - "5003:5000"

  # Container do NGINX (proxy reverso / load balancer)
  nginx:
    image: nginx:latest
    container_name: loadbalancer
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - "80:80"                     # Porta padrão do HTTP
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Monta arquivo de config do NGINX
