version: '3.8'

services:  # Seção onde definimos os serviços (containers)

  # Primeiro container da aplicação
  app1:
    build: ./projeto-web            # Caminho para o Dockerfile da aplicação
    container_name: app1            # Nome do container no Docker (facilita identificar)
    environment:
      SERVER_NAME: "Servidor 1"     # Variável de ambiente que será usada na aplicação Flask
    ports:
      - "5001:5000"                 # Porta externa 5001 → porta interna 5000

  # Segundo container da aplicação
  app2:
    build: ./projeto-web
    container_name: app2
    environment:
      SERVER_NAME: "Servidor 2"
    ports:
      - "5002:5000"

  # Terceiro container da aplicação
  app3:
    build: ./projeto-web
    container_name: app3
    environment:
      SERVER_NAME: "Servidor 3"
    ports:
      - "5003:5000"

  # Container do NGINX (proxy reverso / load balancer)
  nginx:
    image: nginx:latest             # Usa a imagem mais recente do NGINX
    container_name: loadbalancer    # Nome do container do NGINX
    depends_on:
      - app1
      - app2
      - app3                        # Garante que o NGINX só suba após os apps
    ports:
      - "80:80"                     # Porta 80 do host → porta 80 do container (HTTP padrão)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        # Monta o arquivo de configuração do NGINX no container
